anime-relations.txt
For HorribleSubs,
I don't know how I forgot to include this change in my PR before, even though I said I changed it lol...
=> Add "Watashi ni Tenshi ga Maiorita! Special"

anime-relations.txt
=> Add "Diamond no Ace Second Season OVA"

anime-relations.txt
PAS titled their second season of Beastars with "[PAS] Beastars S2 - 13"  and the numbering starts at 13.
=> [PAS] Beastars 2nd Season

anime-relations.txt
Numbering of AnimeLab and RH releases
=> Add "Suzumiya Haruhi no Yuuutsu (2009)"

anime-relations.txt
For releases that use the anidb format, where all 3 movies are in one entry.
https://anidb.net/anime/8357
=> Add Kizumonogatari

anime-relations.txt
Format used by [SubsPlease] (ep. 12 to 24 -> 2nd season 1-13).
=> Update entry for Yuukoku no Moriarty 2nd season

anime-relations.txt
Didn't update the date because it's still the 6th in America, albeit not for me.
=> Add another "Tensei shitara Slime Datta Ken 2nd Season Part 2" relation

anime-relations.txt
First pull request, hope it works.
=> Hanyou no Yashahime: Sengoku Otogizoushi - Ni no Shou

anime-relations.txt
Tested with SubsPlease's release.
=> Genjitsu Shugi Yuusha no Oukoku Saikenki 2nd Season

anime-relations.txt
Used by SubsPlease and basically all other releases.
=> Add Kaginado Season 2

anime-relations.txt
First time doing this, let me know if I made any mistakes ^^
=> Add Kanojo, Okarishimasu 2nd Season

anime-relations.txt
=> Add Jojo Stone Ocean Part 2

anime-relations.txt
=> Add Spy x Family Part 2

anime-relations.txt
=> Legend of the Galactic Heroes (SubsPlease)

anime-relations.txt
Note: Part 2 and Part 3 are combined in AniList
=> Add Jojo Stone Ocean Part 3 and Update Part 2

anime-relations.txt
=> Danmachi S4 Part 2

anime-relations.txt
=> Mononogatari 2nd Season and Sugar Apple Fairy Tale Part 2

anime-relations.txt
e.g. `[SubsPlease] Arknights - Fuyukomori Kaerimichi - 09 (1080p) [12406FC7].mkv`
=> Add "Arknights: Fuyukomori Kaerimichi"

anime-relations.txt
GJ.Y fansub published in [ouo.si](https://ouo.si/view/3227).
File: `[GJ.Y] 女朋友 and 女朋友 第二季 / Kanojo mo Kanojo Season 2 - 13 (Baha 1920x1080 AVC AAC MP4)`
=> Add Kanojo mo Kanojo Season 2

anime-relations.txt
For SubsPlease, most probably raws and encodes of SP as well.
=> Add "Boku no Kokoro no Yabai Yatsu Season 2"

anime-relations.txt
For SubsPlease, potentially raws and encodes
=> Add "High Card Season 2"

anime-relations.txt
For SubsPlease, raws and encodes.
=> Add "Urusei Yatsura (2022) 2nd Season"

anime-relations.txt
For SubsPlease, raws and encodes.
Currently episode number for season 2 is unknown, will make a pull request with the correct range when we get the info.
=> Add "Hikari no Ou Season 2"

anime-relations.txt
Add "Tensei Kizoku, Kantei Skill de Nariagaru 2nd Season"
=> Add "Tensei Kizoku, Kantei Skill de Nariagaru 2nd Season"

anime-relations.txt
Add Rurouni Kenshin: Meiji Kenkaku Romantan - Kyoto Douran
=> Add Rurouni Kenshin: Meiji Kenkaku Romantan - Kyoto Douran

anime-relations.txt
SubsPlease uses EP13 and 14 for the Specials
=> Add Elf-san wa Yaserarenai. Specials

anime-relations.txt
Add "Hyakushou Kizoku Specials"
Add "Hyakushou Kizoku S2"
For Seigyoku subs
=> Add Hyakushou Kizoku Specials and S2

anime-relations.txt
Episode count is not known at this point.
=> Added Hyakkano Season 2

anime-relations.txt
For some reason AniList separate the entry while MyAnimeList and Kitsu don't.
I'm new to this repo, so pardon me if I'm doing something wrong
=> Add redirect for Re:Zero Break Time Season 2 Part 2

anime-relations.txt
Adding rule for Wind Breaker season 2.
Fansub group is [SubsPlease], but it also looks like it's numbered the same even on CR.
=> Add Wind Breaker S2

anime-relations.txt
=> Add Arknights: Rise from Ember
